[programs.localnet]
cattoverse_backend = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/cwkang/.config/solana/id.json"

[scripts]
# test = "yarn run mocha -t 1000000 tests/"
test = "yarn node tests/cattoverse-backend.js"

