[programs.devnet]
cattoverse_backend = "5Sd7zzjsxKPZWT3FnYxHprUqNGzNbXhpEwKbyJ7mr9sS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/cwkang/.config/solana/id.json"

[scripts]
# test = "yarn run mocha -t 1000000 tests/"
test = "yarn node tests/cattoverse-backend.js"

